### ISSUE TITLE
import order and vendors

### ISSUE THREAD

**Issue by robsonsobral** [HugoGiraudel/sass-boilerplate#16]
Hi (again/yet)!

Shouldn't the `vendor` folder be the first one to be imported? We can put a lot of things inside it, not only css. Let's say I want to include [Sass Blend Modes](https://github.com/heygrady/scss-blend-modes). They're functions, which I could use to modify my own variables and functions. I need them loaded before my config files.

Thank you (again/yet), Hugo!

**Comment by robsonsobral** [comment]
I just found [this commit](https://github.com/HugoGiraudel/sass-boilerplate/commit/b072e79e050e36178c00eb979a5bd466c9496c77), but I don't understand its reason. I'm sorry.

**Comment by HugoGiraudel** [comment]
Hello Robson.

The reason why vendors are imported after abstracts is to be able to configure them. Vendors usually use the `!default` flag in their variable definitions, making it possible to define them only they are not defined already. Because of that, we import vendors after the abstracts folder.

> They're functions, which I could use to modify my own variables and functions.

This is bad practice and likely an anti-pattern. A function call should not modify any global element. Ideally it should be pure, which means it takes some arguments, and gives back a result without any side-effect or dependency.

**Comment by robsonsobral** [comment]
Can't a `!default` variable be overridden?

**Comment by HugoGiraudel** [comment]
That’s the whole point.

**Comment by robsonsobral** [comment]
Thank you again.
